# Aula 2 - Warm-up de Python e Numpy

### Treinando conceitos de Tupla

#### W2.4 Crie uma tupla com os números inteiros entre 0 e 10. Crie a tupla manualmente, sem nenhum laço(loop).

In [2]:
# Faça aqui
t1 = (0,1,2,3,4,5,6,7,8,9,10)
# solucao alternativa
t2 = tuple(range(0,11))

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)


In [3]:
# Faça uma iteração sobre a tupla da célula anterior e 
# imprima o valor de cada elemento elevado ao quadrado.
for i in t1:
    print(i**2)

0
1
4
9
16
25
36
49
64
81
100


### Treinando conceitos de Set

In [5]:
# Considere os seguintes conjuntos
c1 = {1, 2, 3, 4, "a", "b", "c"}
c2 = {3, 4, 5, 6, "a", "e"}

#### W2.5 Escreva um código que cria a união dos conjuntos c1 e c2

In [9]:
# Faça aqui
c1.union(c2)

{1, 2, 3, 4, 5, 6, 'a', 'b', 'c', 'e'}

#### W2.6 Escreva um código que cria a intersecção dos conjuntos c1 e c2

In [10]:
# Faça aqui
c1.intersection(c2)

{3, 4, 'a'}

### Treinando conceitos de dicionário (dict) em python

#### W2.7 Criar um dicionário que represente o conteúdo da tabela abaixo

| Nome       | Endereço     | Telefone     |
| :------------- | :----------: | -----------: |
|  Jose da Silva | Rua 2, n. 39   | 119865563    |

In [12]:
# Faça aqui
d = {'nome': 'Jose da Silva', 'Endereço': "Rua 2, n. 39", "Telefone": "119865563"}
# Ou
d = {'nome': 'Jose da Silva', 'Endereço': "Rua 2, n. 39", "Telefone": 119865563}

#### W2.8 Jose da Silva mudou seu número de telefone para 1187662330. Altere este valor no dicionário que você acabou de criar

In [13]:
# Faça aqui
d["Telefone"] = 119865563

#### W2.9 Crie um atributo CPF no dicionário da célula acima e adicione o CPF do Jose da Silva: 495.152.344-90

In [14]:
# Faça aqui
d["CPF"] = "495.152.344-90"

#### W2.10 Remova o atributo Endereço desse dicionário

In [15]:
# Faça aqui
del d["Endereço"]

#### W2.11 Criar uma lista de dicionários que represente o conteúdo da tabela abaixo

| Nome       | Endereço     | Telefone     | CPF |
| :------------- | :----------: | -----------: | -----------: |
|  Jose da Silva | Rua 2, n. 39   | 119865563    | 495.152.344-90
|  Roberto da Araujo | Av 2, n. 2010   | 389912353    | 755.223.432-10
|  Maria Almeida | Rua Jau, n. 309   | 139845162    | 131.223.415-12
|  Joaquim Pereira | Av Sete de Setembro, n. 5240   | 329912633    | 456.214.616-67

In [19]:
# Faça aqui
l = [
    {"nome": "Jose da Silva", "Endereço": "Rua 2, n. 39", "Telefone": "119865563", "CPF": "495.152.344-90"},
    {"nome": "Roberto da Araujo", "Endereço": "Av 2, n. 2010", "Telefone": "389912353", "CPF": "755.223.432-10"},
    {"nome": "Maria Almeida", "Endereço": "Rua Jau, n. 309", "Telefone": "139845162", "CPF": "131.223.415-12"},
    {"nome": "Joaquim Pereira", "Endereço": "Av Sete de Setembro, n. 5240" , "Telefone": "329912633", "CPF": "456.214.616-67"}
  ]

#### W2.12 Considerando a lista de dicionarios do exercicio anterior, remova o dicionário do Jose da Silva desta lista.

In [21]:
# Faça aqui
l.pop(0)
print(l)

[{'nome': 'Roberto da Araujo', 'Endereço': 'Av 2, n. 2010', 'Telefone': '389912353', 'CPF': '755.223.432-10'}, {'nome': 'Maria Almeida', 'Endereço': 'Rua Jau, n. 309', 'Telefone': '139845162', 'CPF': '131.223.415-12'}, {'nome': 'Joaquim Pereira', 'Endereço': 'Av Sete de Setembro, n. 5240', 'Telefone': '329912633', 'CPF': '456.214.616-67'}]


#### W2.13 Considerando a lista de dicionarios do exercicio anterior, usando um loop, remova todos os telefones desta lista de dicionários


In [22]:
# Faça aqui
for e in l:
    del e['Telefone']

print(l)

[{'nome': 'Roberto da Araujo', 'Endereço': 'Av 2, n. 2010', 'CPF': '755.223.432-10'}, {'nome': 'Maria Almeida', 'Endereço': 'Rua Jau, n. 309', 'CPF': '131.223.415-12'}, {'nome': 'Joaquim Pereira', 'Endereço': 'Av Sete de Setembro, n. 5240', 'CPF': '456.214.616-67'}]


### Treinando a função zip

#### W2.14 Crie um código que execute as instruções solicitadas abaixo

In [23]:
# Considere as seguintes listas
letras = ["Jan", "Fev", "Mar"]
numeros = [1000, 2000, 3000]

# Usando a função zip e um loop do tipo for, crie um dicionário cuja chave sejam 
# os elementos da lista letras e o valor os elementos da lista numeros
# Resultado esperado: {"Jan": 1000, "Fev": 2000, "Mar": 3000}
result = {}
for l, n in zip(letras, numeros):
    result[l] = n
print(result)

{'Jan': 1000, 'Fev': 2000, 'Mar': 3000}


### Treinando instruções inline e list comprehension

#### W2.15 Escreva uma instrução if else na forma inline que teste o tamanho de uma string e retorne True caso o seu tamanho seja maior que 5, e Falso caso contrário.
#### Dica - Sintaxe: valor_se_verdadeiro if condicao else valor_se_falso

In [24]:
# Faça aqui
s = "asdfasd"
r = True if len(s) > 5 else False
print(r)


True


#### W2.16 Escreva um list comprehension, ou seja, uma instrução de loop (for) na forma inline que gere a lista [1, 4, 9, 16, 25, 36, 49, 64,  81, 100]
#### Dica - Sintaxe: [ OPERACAO_COM_X for X in SEQUENCIA ]

In [25]:
# Faça aqui
[x**2 for x in range(1, 11)]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

#### W2.17 Escreva um list comprehension, ou seja, uma instrução de loop (for) na forma inline que gere a lista [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
#### Dica - Sintaxe: [ OPERACAO_COM_X for X in SEQUENCIA ]

In [26]:
# Faça aqui
[x for x in range(1, 20, 2)]

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

#### W2.18 Escreva um dict comprehension, ou seja, uma instrução de loop (for) na forma inline que gere um dicionário. O dicionário deve conter palavras nas suas chaves e nos valores, os respectivos tamanhos (quantidade de letras) das suas chaves.
#### Exemplo: {"carro": 5, "moto": 4, "trem": 4, "aviao": 5, "bicicleta": 9} 

In [27]:
palavras = ["carro", "moto", "trem", "aviao", "bicicleta"]
# Faça aqui
{k:len(k) for k in palavras}

{'carro': 5, 'moto': 4, 'trem': 4, 'aviao': 5, 'bicicleta': 9}

## NumPy Arrays


In [29]:
# Importe a biblioteca numpy
import numpy as np

### Treinando a criação de arrays numpy

#### W2.19 Execute as instruções da célula abaixo

In [38]:
# 1) Crie um array unidimensional a partir da lista [6, 7.5, 8, 0, 1] e imprima o tipo do dado armazenado nele.
ar = np.array([6, 7.5, 8, 0, 1])
print(ar.dtype)
# 2) Crie um array bidimensional a partir da lista [[1, 2, 3, 4], [5, 6, 7, 8]] e imprima o shape (forma) dele.
ar2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(ar2.shape)
# 3) Crie um array unidimensional de zeros com 10 elementos.
z = np.zeros(10)
print(z)

float64
(2, 4)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Treinando conversão de tipos (cast)

#### W2.20 Realize a conversão de tipos especificada na célula abaixo

In [45]:
# Considere o seguinte array
num_str = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
# 1) Converta os dados do array num_str para float
arr_float = num_str.astype(float) 
print(arr_float)
# 2) Converta os dados do array do item 1 para int
arr_int = arr_float.astype(int) 

# 3) Imprima o tipo do dado do array que foi convertido para inteiro 
print(arr_int)

[ 1.25 -9.6  42.  ]
[ 1 -9 42]


### Treinando operações vetorizadas em ndarrays
#### W2.21 Sem utilizar laços (loops), execute as instruções da célula abaixo

In [48]:
# Considere o seguinte array
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr2 = np.array([[9, 12, 13, 14], [15, 16, 17, 18]])

# 1) Multiplique todos os elementos do array arr1 por 10
print(arr1 * 10)
# 2) Eleve ao quadrado todos os elementos do arr1
print(arr1 ** 2)
# 3) Calcule a hipotenusa de triangulos cujos catetos estão definidos nos arrays arr1 e arr2.
#    Ou seja, calcule a raiz quadrada da soma dos quadrados dos elementos de arr1 e arr2.
print((arr1**2 + arr2**2)**0.5)


[[10 20 30 40]
 [50 60 70 80]]
[[ 1  4  9 16]
 [25 36 49 64]]
[[ 9.05538514 12.16552506 13.34166406 14.56021978]
 [15.8113883  17.08800749 18.38477631 19.6977156 ]]


### Treinando a seleção de elementos (slicing) em arrays numpy

#### W2.22 Sem utilizar laços (loops), execute as instruções da célula abaixo

In [54]:
# Considere o seguinte array
arr3 = np.array([[1, 2, 3, 4, 10, 11, 12, 13], [5, 6, 7, 8, 10, 11, 12, 13],
                [1, 2, 3, 4, 10, 11, 12, 13], [5, 6, 7, 8, 10, 11, 12, 13]])

# 1) Selecione e imprima os elementos que estão nas colunas de índice 0 e 1 
#    de todas as linhas desse array bidimensional
print(arr3[:, [0,1]])

# 2) Atribua o valor 1000 a todos os elementos que estão nas colunas de índice 0 e 1 
#    de todas as linhas desse array bidimensional
arr3[:, [0,1]] = 1000
print(arr3)
# 3) Selecione e imprima os elementos que estão nas colunas de índice 1 até a penúltima coluna
# de todos os elementos desse array bidimensional
print(arr3[:, 1:-1])

# 4) Atribua zero para todos os elementos que estão nas linhas ímpares do array arr3

arr3[1::2, :] = 0
print(arr3)

[[1 2]
 [5 6]
 [1 2]
 [5 6]]
[[1000 1000    3    4   10   11   12   13]
 [1000 1000    7    8   10   11   12   13]
 [1000 1000    3    4   10   11   12   13]
 [1000 1000    7    8   10   11   12   13]]
[[1000    3    4   10   11   12]
 [1000    7    8   10   11   12]
 [1000    3    4   10   11   12]
 [1000    7    8   10   11   12]]
[[1000 1000    3    4   10   11   12   13]
 [   0    0    0    0    0    0    0    0]
 [1000 1000    3    4   10   11   12   13]
 [   0    0    0    0    0    0    0    0]]


### Treinando outras funções numpy

#### W2.23 Usando a função np.sum, calcule a soma dos elementos de cada linha do array criado abaixo. 

In [55]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Faça aqui
np.sum(arr2d, axis=1)

array([ 6, 15, 24])

#### W2.24 Usando a função np.mean, calcule a média dos elementos de cada coluna do array criado abaixo. 

In [56]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Faça aqui
np.mean(arr2d, axis=0)

array([4., 5., 6.])

#### W2.25 Usando a função np.any, mostre quais colunas do array criado abaixo possuem pelo menos um valor diferente de zero. 

In [57]:
arr4 = np.array([[0, 0, 0], [0, -5, -6], [0, -8, -9]])
# Faça aqui
arr4.any(axis=0)

array([False,  True,  True])

#### W2.26 Usando a função np.argmax, retorne o índice das colunas que contém o valor máximo de cada linha do array criado abaixo. 

In [58]:
arr2d = np.array([[10, 2, 3], [4, 5, 6], [7, 8, 9]])
# Faça aqui
arr2d.argmax(axis=1)

array([0, 2, 2], dtype=int64)

#### W2.27 Crie um array unidimensional de 120 elementos, cujos valores sejam sequenciais iniciando em 20 e terminando em 139.
#### Dica: use a função np.arange(). Ela tem a mesma sintaxe (argumentos) da função range do python estudada em aula.

In [60]:
# Faça aqui
arr5 = np.arange(20, 140)
print(arr5)

[ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109
 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127
 128 129 130 131 132 133 134 135 136 137 138 139]


#### W2.28 Altere a estrutura do array do exercício anterior. Transformando-o num array bidimensional de 12 linhas e 10 colunas.
#### Dica: Use o método (função) ndarray.reshape(), passando as dimensões (linhas e colunas) como argumento.

In [61]:
# Faça aqui
arr5.reshape([12,10])

array([[ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139]])

#### W2.29 Selecione os numeros pares do array definido abaixo
#### Dica: pra testar se um número é par, use a seguinte expressão: n % 2 == 0. Neste caso, se n for par o resultado a expressão é True, pois o operador porcentagem (%) retorna o resto da divisão.

In [62]:
arr = np.arange(100)
# Faça aqui
arr[arr %2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])